version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    shm_size: "1gb"
    env_file:
      - ./devcontainer.env
    volumes:
      - ../..:/workspaces:cached
      - bundle-data-volume:/usr/local/bundle
    depends_on:
      - db
      - redis
    command: sleep infinity

  db:
    image: mysql:8
    restart: unless-stopped
    command:
      [
        "mysqld",
        "--sql_mode=TRADITIONAL",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default_authentication_plugin=mysql_native_password",
        "--bind-address=0.0.0.0"
      ]
    volumes:
      - mysql-data-volume:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"

volumes:
  mysql-data-volume:
  bundle-data-volume:
