name: Pronto
on: [pull_request]

jobs:
  pronto:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          git fetch --no-tags --prune --depth=100 origin +refs/heads/*:refs/remotes/origin/*

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1

      - name: Find gem path
        id: gem-path
        run: echo "::set-output name=path::$(gem env gemdir)"

      - name: Cache gems
        id: cache-gems
        uses: actions/cache@v3
        with:
          path: ${{ steps.gem-path.outputs.path }}
          key: ${{ runner.os }}-gems-${{ hashFiles(find ${{ steps.gem-path.outputs.path }} -type f -print0 | xargs -0 md5sum) }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Setup Pronto
        if: steps.cache-gems.outputs.cache-hit != 'true'
        run: |
          gem install octokit -v 4.25.1
          gem install pronto pronto-brakeman pronto-flay pronto-reek

      - name: Run Pronto
        run: pronto run -f github_pr_review -c origin/${{ github.base_ref }}
        env:
          PRONTO_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          PRONTO_GITHUB_ACCESS_TOKEN: "${{ github.token }}"